package iu;

import java.awt.Frame;
import java.util.ArrayList;
import logica.Agenda;
import logica.Telefono;

public class ListaTelefonosDialog extends javax.swing.JDialog {

    private ArrayList<Telefono> telefonos;

    /**
     * Creates new form ListaTelefonos
     */
    public ListaTelefonosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ListaTelefonosDialog(java.awt.Frame parent, boolean modal, ArrayList<Telefono> telefonos) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setListTitle(parent);
        this.telefonos = telefonos;
        mostrarTelefonos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_telefonos = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("Telefonos de la agenda");

        jScrollPane1.setViewportView(lista_telefonos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista_telefonos;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables

    private void mostrarTelefonos() {
        String[] telefonos = new String[this.telefonos.size()];
        for (int i = 0; i < this.telefonos.size(); i++) {
            telefonos[i] = this.telefonos.get(i).toString() + " - " + this.telefonos.get(i).getContacto().getNombre();
        }
        lista_telefonos.setListData(telefonos);
    }

    private void setListTitle(Frame parent) {
        try {
            AgendaFrame af = (AgendaFrame) parent;
            setTitle(af.getTitle());
        } catch (Exception e) {
            setTitle("Agenda - Lista de teléfonos");
        }
    }
}
