/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author docenteFI
 */
public class PanelDatosPartida extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatosPartida
     */
    public PanelDatosPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(20, 30, 41, 16);

        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(110, 50, 41, 16);

        jButton1.setText("jButton1");
        add(jButton1);
        jButton1.setBounds(70, 160, 79, 25);

        jTextField1.setText("jTextField1");
        add(jTextField1);
        jTextField1.setBounds(170, 170, 69, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
