/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPartida;
import controlador.VistaPartida;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JSplitPane;

/**
 *
 * @author docenteFI
 */
public class VentanaPartida extends javax.swing.JFrame implements VistaPartida,ActionListener{

    /**
     * Creates new form VentanaPartida
     */
    private ControladorPartida controlador;
    private JSplitPane split;
    public VentanaPartida() {
        
        initComponents();
        
        split = new JSplitPane();
        split.setTopComponent(new PanelDatosPartida());
        setContentPane(split);
        controlador = new ControladorPartida(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void mostrarTablero(int tam, ArrayList<CasilleroPanelTablero> lista) {
        PanelTablero p = new PanelTablero();
      p.mostrarTablero(tam, lista, this);
      //setContentPane(p);
      split.setBottomComponent(p);
      split.setDividerLocation(300);
      validate();
    }
        @Override
    public void actionPerformed(ActionEvent e) {
        BotonCasillero b = (BotonCasillero) e.getSource();
        CasilleroPanelTablero c = b.getCasillero();
        controlador.destapar(c);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
