/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorContador;
import controlador.VistaContador;

/**
 *
 * @author docenteFI
 */
public class VistaContadorDos extends javax.swing.JDialog implements VistaContador{

    /**
     * Creates new form VistaContadorDos
     */
    private ControladorContador controlador;
    public VistaContadorDos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorContador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta = new javax.swing.JLabel();
        mensajes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        etiqueta.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        etiqueta.setForeground(new java.awt.Color(255, 102, 51));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("VALOR:");
        getContentPane().add(etiqueta);
        etiqueta.setBounds(20, 50, 350, 100);

        mensajes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mensajes.setText("Mensaje:");
        getContentPane().add(mensajes);
        mensajes.setBounds(50, 220, 320, 70);

        setBounds(0, 0, 437, 395);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='s' || evt.getKeyChar()=='S'){
            mensajes.setText("");
            controlador.sumar();
        }
        if(evt.getKeyChar()=='r' || evt.getKeyChar()=='R'){
            mensajes.setText("");
            controlador.restar();
            
        }
    }//GEN-LAST:event_formKeyPressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel mensajes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarValor(String valor) {
        etiqueta.setText(valor);
    }

    @Override
    public void mostrarError(String mensaje) {
        mensajes.setText(mensaje);
    }
}
