/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import logica.Fachada;
import logica.Usuario;

/**
 *
 * @author docenteFI
 */
public class MonitorUsuarios extends javax.swing.JDialog implements Observer{

    /**
     * Creates new form MonitorUsuarios
     */
    private Fachada logica = Fachada.getInstancia();
    private ArrayList<Usuario> logueados ;
    
    public MonitorUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        logica.addObserver(this);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 400, 240);

        jLabel1.setText("DOBLRE CLICK PARA VER AGENDA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 300, 290, 20);

        setBounds(0, 0, 487, 376);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        logica.deleteObserver(this);
    }//GEN-LAST:event_formWindowClosing

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            mostrarAgenda();
        }
    }//GEN-LAST:event_listaMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object evento) {
        if(evento.equals(Fachada.Eventos.usuario) || evento.equals(Fachada.Eventos.agenda)){
            mostrar();
        }
    }

    private void mostrar() {
        logueados = new ArrayList(logica.getLogueados());
        ArrayList<String> listado = new ArrayList();
        for(Usuario u:logueados){
            listado.add(formatear(u));
        }
        lista.setListData(listado.toArray());
    }

    private String formatear(Usuario u) {
        return u.getNombreCompleto() + " - " + u.getAgenda().getContactos().size() + " contacto(s)";
    }

    private void mostrarAgenda() {
            int pos = lista.getSelectedIndex();
            if(pos!=-1){
                new MonitorAgenda(null,false,logueados.get(pos).getAgenda()).setVisible(true);
            }
    }
}
