/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package divisionlogica;

/**
 *
 * @author docenteFI
 */
public class VentanaNumeros extends javax.swing.JFrame {

    private LogicaNumeros logica = new LogicaNumeros();

    /**
     * Creates new form VentanaNumeros
     */
    public VentanaNumeros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        establecer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Cantidad");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 60, 30);
        getContentPane().add(cantidad);
        cantidad.setBounds(80, 10, 59, 40);

        establecer.setText("Establecer");
        establecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                establecerActionPerformed(evt);
            }
        });
        getContentPane().add(establecer);
        establecer.setBounds(160, 10, 90, 40);

        jLabel2.setText("Numero");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 50, 30);
        getContentPane().add(numero);
        numero.setBounds(80, 60, 60, 40);

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar);
        ingresar.setBounds(160, 60, 90, 40);

        jScrollPane1.setViewportView(resultado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 230, 170);

        setBounds(0, 0, 298, 365);
    }// </editor-fold>//GEN-END:initComponents

    private void establecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_establecerActionPerformed
        establecer();
    }//GEN-LAST:event_establecerActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        ingresar();
    }//GEN-LAST:event_ingresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton establecer;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numero;
    private javax.swing.JList resultado;
    // End of variables declaration//GEN-END:variables

    private void establecer() {
        int c = Integer.parseInt(cantidad.getText());
        logica.setCantidad(c);
    }

    private void ingresar() {
        int n = Integer.parseInt(numero.getText());
        logica.ingresar(n);
        if (logica.fin()) {
            mostrarResutado();
        }
    }

    private void mostrarResutado() {
        resultado.setListData(logica.getResultado().toArray());
    }
}
