/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package divisionlogica;

import java.util.ArrayList;

/**
 *
 * @author docenteFI
 */
public class VentanaNumeros2 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaNumeros2
     */
    public VentanaNumeros2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        datos = new javax.swing.JTextField();
        procesar = new javax.swing.JButton();
        resultado = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Datos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 50, 40);
        getContentPane().add(datos);
        datos.setBounds(80, 40, 200, 40);

        procesar.setText("Procesar");
        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });
        getContentPane().add(procesar);
        procesar.setBounds(300, 40, 80, 40);

        getContentPane().add(resultado);
        resultado.setBounds(80, 110, 200, 30);

        jLabel2.setText("Resultado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 48, 30);

        setBounds(0, 0, 411, 222);
    }// </editor-fold>//GEN-END:initComponents

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed
        procesar();
    }//GEN-LAST:event_procesarActionPerformed

    private LogicaNumeros logica = new LogicaNumeros();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton procesar;
    private javax.swing.JComboBox resultado;
    // End of variables declaration//GEN-END:variables

    private void procesar() {
        String[] numeros = datos.getText().split(" ");
        logica.setCantidad(numeros.length);
        for (String numero : numeros) {
            logica.ingresar(Integer.parseInt(numero));
        }
        if (logica.fin()) {
            mostrarResultado();
        }
    }

    private void mostrarResultado() {
        resultado.removeAllItems();
        ArrayList<Integer> res = logica.getResultado();
        for(int n : res){
            resultado.addItem(n);
        }
    }
}
