/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package divisionlogica;

/**
 *
 * @author docenteFI
 */
public class VentanaContador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaContador
     */
    private Contador contador = new Contador();
    
    public VentanaContador() {
        initComponents();
        setLocationRelativeTo(null);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        mas = new javax.swing.JButton();
        menos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        display.setEditable(false);
        display.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(display);
        display.setBounds(110, 40, 180, 170);

        mas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        mas.setText("+");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        getContentPane().add(mas);
        mas.setBounds(103, 240, 80, 70);

        menos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        getContentPane().add(menos);
        menos.setBounds(220, 240, 80, 70);

        setBounds(0, 0, 416, 388);
    }// </editor-fold>//GEN-END:initComponents

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        // TODO add your handling code here:
        contador.sumar();
        mostrar();
        
    }//GEN-LAST:event_masActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        contador.restar();
        mostrar();
    }//GEN-LAST:event_menosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField display;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    // End of variables declaration//GEN-END:variables

    private void mostrar() {
        display.setText(contador.getValor() + "");
    }
}
