/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Agenda;
import logica.AgendaException;
import logica.Contacto;
import logica.Fachada;
import logica.Tipo;
import logica.Usuario;

/**
 *
 * @author docenteFI
 */
public class AgendaFrame extends javax.swing.JFrame {

    /**
     * Creates new form AgendaFrame
     */
    private Agenda agenda;
    private Contacto nuevo = new Contacto();

    public AgendaFrame(Usuario u) {
        initComponents();
        setLocationRelativeTo(null);
        agenda = u.getAgenda();
        setTitle("Agenda de " + agenda.getDueño().getNombreCompleto());
        cargarTipos();
        muestroContactos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        agregarTelefono = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        telefonos = new javax.swing.JList();
        crearContacto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactos = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 90, 20);
        getContentPane().add(nombre);
        nombre.setBounds(70, 20, 150, 30);

        jLabel2.setText("Numero");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 70, 20);
        getContentPane().add(numero);
        numero.setBounds(70, 110, 150, 30);

        jLabel3.setText("Tipo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 60, 14);

        getContentPane().add(tipo);
        tipo.setBounds(70, 170, 150, 30);

        agregarTelefono.setText("Agregar");
        agregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarTelefono);
        agregarTelefono.setBounds(100, 220, 90, 30);

        jScrollPane1.setViewportView(telefonos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 160, 130);

        crearContacto.setText("Crear");
        crearContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearContactoActionPerformed(evt);
            }
        });
        getContentPane().add(crearContacto);
        crearContacto.setBounds(90, 430, 110, 40);

        jScrollPane2.setViewportView(contactos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(280, 60, 150, 340);

        jLabel4.setText("Contactos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 20, 90, 14);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(300, 430, 90, 50);

        setBounds(0, 0, 480, 554);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTelefonoActionPerformed
        // TODO add your handling code here:
        agregarTelefono();
    }//GEN-LAST:event_agregarTelefonoActionPerformed

    private void crearContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearContactoActionPerformed
        // TODO add your handling code here:
        crearContacto();
    }//GEN-LAST:event_crearContactoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        salir();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarTelefono;
    private javax.swing.JList contactos;
    private javax.swing.JButton crearContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero;
    private javax.swing.JButton salir;
    private javax.swing.JList telefonos;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables

    private void cargarTipos() {
        ArrayList<Tipo> tipos = Fachada.getInstancia().getTipos();
        for (Tipo t : tipos) {
            tipo.addItem(t);
        }
    }

    private void agregarTelefono() {
        String nro = numero.getText();
        Tipo t = (Tipo) tipo.getSelectedItem();
        try {
            nuevo.agregar(nro, t);
            mostrarTelefonos();
        } catch (AgendaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void mostrarTelefonos() {
        telefonos.setListData(nuevo.getTelefonos().toArray());
    }

    private void crearContacto() {
        nuevo.setNombre(nombre.getText());
        try {
            agenda.agregar(nuevo);
            muestroContactos();
            nuevo = new Contacto();
            mostrarTelefonos();
            nombre.setText("");
        } catch (AgendaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void muestroContactos() {
        contactos.setListData(agenda.getContactos().toArray());
    }

    private void salir() {
        Fachada.getInstancia().logout(agenda.getDueño());
        dispose();
    }
}
